replicaCount: 1
image:
  repository: mysql
  tag: 8.0
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
service:
  type: NodePort
  port: 3306
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
analytics: true
redis:
    enabled: true
keycloak:
    enabled: true
obf-ui:
    enabled: true
obf-backend:
    enabled: true
env:
  MYSQL_USER: keycloak
  MYSQL_PASSWORD: keycloak
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: keycloak
  
redis:
  replicaCount: 1
  image:
    repository: redis
    tag: "5.0.5"
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  service:
    type: NodePort
    port: "6379"
  ingress:
    enabled: false
    annotations: {}
    hosts:
    - host: chart-example.local
      paths: []
    tls: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  
keycloak:
  replicaCount: 1
  image:
    repository: jboss/keycloak
    tag: "latest"
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  service:
    type: NodePort
    port: "8080"
  ingress:
    enabled: false
    annotations: {}
    hosts:
    - host: chart-example.local
      paths: []
    tls: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  env:
    KEYCLOAK_LOGLEVEL: WARN
    ROOT_LOGLEVEL: WARN
    DB_VENDOR: MYSQL
    DB_ADDR: mysql
    DB_USER: root
    DB_PASSWORD: root
    JGROUPS_DISCOVERY_PROTOCOL: kubernetes.KUBE_PING
    JGROUPS_DISCOVERY_PROPERTIES: 'port_range=0,dump_requests=true'
    PROXY_ADDRESS_FORWARDING: 'true'
    connectTimeout: '600000'
    KEYCLOAK_USER: admin
    KEYCLOAK_PASSWORD: admin
    remoteTimeout: '600000'
    MYSQL_PORT: '3306'

frontend-container:
  replicaCount: 1
  image:
    repository: tareshsoni/obf-ui
    tag: "v19"
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  service:
    type: NodePort
    port: "80"
  ingress:
    enabled: false
    annotations: {}
    hosts:
    - host: chart-example.local
      paths: []
    tls: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  env: 
   KEYCLOAK_URL: 'http://keycloak.34.93.217.255.nip.io/auth'
   KEYCLOAK_REALM: activiti
   KEYCLOAK_CLIENTID: activiti
   OBF_HOST_BACKEND: 'http://backend.34.93.217.255.nip.io'
   OBF_HOST_KIBANA: 'http://34.85.46.112:30601'
   
backend-container:
  replicaCount: 1
  image:
    repository: 9572343416/obf-backend 
    tag: "v1"
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  service:
    type: NodePort
    port: "8082"
  ingress:
    enabled: false
    annotations: {}
    hosts:
    - host: chart-example.local
      paths: []
    tls: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  env:
   AUTH_URI: 'http://keycloak.34.93.217.255.nip.io/auth'
   REALM: activiti
   RESOURCE: activiti
   URI: jdbc:mysql://mysql:3306/obf?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
   DB_USER_NAME: root
   DB_PASSWORD: root
   REDIS_HOST: mysql-redis
   REDIS_PORT: "6379"
  
