apiVersion: v1
kind: PersistentVolume
metadata:
   name: common-pv-1-volume
   labels:
     type: local
spec:
   capacity:
     storage: 1Gi
   accessModes:
    - ReadWriteOnce
   hostPath:
     path: /home/ist/mydata

