apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "mysql.fullname" . }}-{{ .Chart.Version }}
  labels:
    # The "release" convention makes it easy to tie a release to all of the
    # Kubernetes resources that were created as part of that release.
    release: {{ .Release.Name }}
    # This makes it easy to audit chart usage.
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "mysql.name" . }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
   # "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ template "mysql.fullname" . }}
      labels:
        release: {{ .Release.Name }}
        app: {{ template "mysql.name" . }}
      annotations:
        {{- if .Values.enableIstio }}
        "sidecar.istio.io/inject": "false"
        {{- end }}
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: "fission/alpinecurl"
          imagePullPolicy: {{ .Values.pullPolicy }}
          command: ["/bin/sh", "-c", {{ .Files.Get "scripts/test.sh" | quote }}]
          env:
          #setting KEY1 as environment variable in the container,value of KEY1 in container is value1(read from values.yaml)
          - name: KEY1
            value: "Aniruddh"
          - name: KEY2
            value: "Sonsale"
